services:
  - type: web
    name: demo-bilihubs-shop
    env: php
    buildCommand: |
      rm -rf vendor
      composer install --no-interaction --no-dev
      npm ci && npm run build
      php artisan config:clear
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://demo-bilihubs-shop.onrender.com
      - key: SESSION_DOMAIN
        value: ""
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_SAME_SITE
        value: lax
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_CONNECTION
        value:pgsql
      - key: DB_CONNECTION
        value: pgsql
    disk:
      name: laravel-storage
      mountPath: storage/temp_uploads
    autoDeploy: true
    healthCheckPath: /up